Restructured code for better modularity

diff --git a/bin/worklog b/bin/worklog
--- a/bin/worklog
+++ b/bin/worklog
@@ -1,31 +1,43 @@
 #!/bin/bash
 #A simple tool for creating and reading/writing a worklog in your project
 
-if [ "$1" == "ignore" ]; then
-  printf "\n#Ignore worklog\nworklog" >> .gitignore && exit 0
-fi
+function setUpEditor {
+  #Check if standard editor is set, if not, use nano
+  if [ "$EDITOR" == "" ]; then
+    EDITOR=nano
+  fi
 
-#Check if standard editor is set, if not, use nano
-if [ "$EDITOR" == "" ]; then
-  EDITOR=nano
-fi
+  #Check if provided editor is installed, exit if not
+  if [ "$(which $EDITOR)" == "" ]; then
+    echo "\"$EDITOR\" has not been found on your system, aborting"
+    exit 1
+  fi
 
-#Check if provided editor is installed, exit if not
-if [ "$(which $EDITOR)" == "" ]; then
-  echo "\"$EDITOR\" has not been found on your system, aborting"
-  exit 1
-fi
+}
 
-#Check if worklog exists or not
-if [ -f ./worklog ]; then
-  "$EDITOR" ./worklog
-else
+function openLog {
+  searchLog && "$EDITOR" ./worklog
+}
+
+function searchLog {
+  if [ ! -f ./worklog ]; then
+    createLog
+  fi
+}
+
+function createLog {
   printf "No worklog found in \"%s\", create a new one? (yes) " "${PWD##*/}"
   read -r input
 
   if [[ "$input" == "" || "$input" == "yes" || "$input" == "y" ]]; then
     "$EDITOR" ./worklog
   else
-    echo "Aborting"
+    echo "Aborting" && exit 0
   fi
+}
+
+if [ "$1" == "ignore" ]; then
+  printf "\n#Ignore worklog\nworklog" >> .gitignore
+else
+  setUpEditor && openLog
 fi
